### PR TITLE
Upgrade to jupyterlab 2.0.0

### PR DESCRIPTION
**Pull request by j123github**
* Update to final JupyterLab 2.0 versions, bump package to alpha 4

### CODE REVIEW

**Comment by j123github** [comment]
@jonmmease 

Hi. I'm a huge fan of the functionality of Dash and have enjoyed using it from within JupyterLab. 
I've attempted to update the extension so that it works with JupyterLab 2.0. My local testing has worked successfully.

My familiarity with both typescript and JupyterLab extension development is pretty low but I hope that this helps the community leverage this functionality in the new JupyterLab version.

Please let me know if I need to follow alternative steps before this pull request can be merged. I could not find if any specific testing is required.

**Comment by j123github** [comment]
I've uploaded the package to npmjs so you can install a jupyterlab 2.0.1 compatible extension using
```
jupyter labextension install @j123npm/jupyterlab-dash@0.1.0-alpha.4
```

**Comment by jonmmease** [comment]
Thanks for tackling this @j123github, we're close to rolling out a replacement for this library that will include JupyterLab 2.0 support. But if we don't get that released soon, we can publish another version with these changes here.  Thanks again!

**Comment by jonmmease** [comment]
Hi @j123github, the new project will be announced tomorrow, but it's already ready to use at https://github.com/plotly/jupyter-dash.  Thanks again for this contribution! Even though it won't be merged and released, it was a really helpful reference when porting the extension to JupyerLab 2.0 in for the new project.

**Pull request closed without merging**
