### PR TITLE
ability to run jupyterlab-dash on remote jupyter

### PR DESCRIPTION
**Pull request by anhvut**
just call `jupyterlab_dash.AppViewer(host='0.0.0.0')`

### CODE REVIEW

**Review by nathanmargaglio — APPROVED** [review]
I was just about to do the same thing, but figured I'd check the PRs.  This looks good and works for me :+1:

**Comment by jonmmease** [comment]
Hi @anhvut, this should now be possible with https://github.com/plotly/jupyterlab-dash/pull/2 if you pass `hostname` as a kwarg to the `show` function.  In general, I think it would be nice to allow default values of the relevant properties to be specified in the constructor, and then overridden in `show` if needed.

For now, if you want to rebase this on https://github.com/plotly/jupyterlab-dash/pull/2 I'm happy to merge.  Just make sure that if hostname is specified in `show` that it takes precedence over the hostname specified in the constructor.

cc @timkpaine

**Comment by anhvut** [comment]
Hello @jonmmease , I have rebased and added precedence for `host` and `port` parameter when theses parameters are specified on show method call. Please note that the parameter name is `host` because it is the one expected by flask.

**Comment by jonmmease** [comment]
Thanks @anhvut, looks great!

**Pull request merged**
